
TrajectoryPlannerROS:
    max_vel_x: 1.5
    min_vel_x: 0.3
    
    max_vel_y: 0.0
    min_vel_y: 0.0

    max_vel_theta: 2.0
    min_vel_theta: -2.0
    min_in_place_vel_theta: 0.0
  
    acc_lim_theta: 3.2
    acc_lim_x: 1.5
    acc_lim_y: 1.5
  
    holonomic_robot: false


    yaw_goal_tolerance: 0.1
    xy_goal_tolerance: 0.2
    latch_xy_goal_tolerance: true


    vx_samples: 20
    vtheta_samples: 40

    path_distance_bias: 1.0
    meter_scoring: true

    publish_cost_grid_pc: true
 